// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConvertMetadata = { title: string | null, author: string | null, thumbnail: string | null, duration: bigint | null, url: string | null, };
