// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipRange } from "./ClipRange";
import type { ProxyConfig } from "./ProxyConfig";

export type DownloadOptions = { cookiesFromBrowser: string | null, customCookies: string | null, proxy: ProxyConfig | null, speedLimit: bigint | null, embedThumbnail: boolean, embedMetadata: boolean, embedSubtitles: boolean, subtitleLangs: string | null, sponsorblockRemove: string | null, youtubePlayerClient: string | null, aria2Connections: number | null, aria2Splits: number | null, maxRetries: number | null, clipRanges: Array<ClipRange> | null, };
