// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryStats = { totalDownloads: number, totalSize: number, totalDuration: number, formatCounts: Record<string, number>, favouritesCount: number, };
