// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadRequest } from "./DownloadRequest";
import type { JobStatus } from "./JobStatus";

export type Job = { id: string, request: DownloadRequest, status: JobStatus, backend: string, createdAt: bigint, startedAt: bigint | null, completedAt: bigint | null, progress: number, downloadedBytes: bigint, totalBytes: bigint | null, speed: bigint | null, eta: bigint | null, tempFiles: Array<string>, retryCount: number, lastError: string | null, title: string | null, thumbnail: string | null, postProcessIndex: number, };
