// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Job } from "./Job";
import type { JobStatus } from "./JobStatus";

export type JobEvent = { "type": "added", "data": { job: Job, } } | { "type": "started", "data": { job_id: string, backend: string, } } | { "type": "progress", "data": { job_id: string, progress: number, downloaded_bytes: bigint, total_bytes: bigint | null, speed: bigint | null, eta: bigint | null, } } | { "type": "statusChanged", "data": { job_id: string, status: JobStatus, } } | { "type": "completed", "data": { job_id: string, output_path: string, title: string | null, thumbnail: string | null, filesize: bigint | null, } } | { "type": "failed", "data": { job_id: string, error: string, retryable: boolean, } } | { "type": "cancelled", "data": { job_id: string, } } | { "type": "paused", "data": { job_id: string, } } | { "type": "resumed", "data": { job_id: string, } };
