// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PodcastProgress = { historyId: string, 
/**
 * "fetching_transcript" | "generating_script" | "narrating" | "mastering" | "complete" | "failed"
 */
step: string, progress: number, error: string | null, };
