// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PodcastSettings = { enabled: boolean, subtitleLang: string, ttsVoice: string, ttsRate: string, claudePrompt: string | null, masteringEnabled: boolean, autoGenerate: boolean, };
