// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TorrentOption = { quality: string | null, codec: string | null, seeders: number | null, 
/**
 * Size in bytes as returned by the API (integer).
 */
sizeBytes: number | null, qualityScore: number | null, magnetUrl: string | null, torrentUrl: string | null, };
