// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TorrentOption = { quality: string | null, codec: string | null, seeders: number | null, 
/**
 * API returns size as a string (e.g. "4.2 GiB")
 */
sizeBytes: string | null, qualityScore: number | null, magnetUrl: string | null, torrentUrl: string | null, };
