// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TorrentSearchResult } from "./TorrentSearchResult";

export type TorrentSearchResponse = { total: number, page: number, results: Array<TorrentSearchResult>, };
