// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TorrentSearchFilters = { query: string, 
/**
 * "movie" | "tv"
 */
contentType: string | null, 
/**
 * "4K" | "1080p" | "720p"
 */
quality: string | null, genre: string | null, year: number | null, minRating: number | null, language: string | null, 
/**
 * "relevance" | "seeders" | "rating" | "date"
 */
sort: string | null, page: number | null, };
