// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TorrentOption } from "./TorrentOption";

export type TorrentSearchResult = { title: string, year: number | null, type: string | null, ratingImdb: string | null, posterUrl: string | null, torrents: Array<TorrentOption>, };
