// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chapter } from "./Chapter";
import type { PlaylistEntry } from "./PlaylistEntry";
import type { Storyboard } from "./Storyboard";
import type { VideoFormat } from "./VideoFormat";

export type UrlInfo = { url: string, title: string | null, thumbnail: string | null, duration: bigint | null, filesize: bigint | null, extractor: string, isPlaylist: boolean, playlistCount: number | null, formats: Array<VideoFormat> | null, mimeType: string | null, entries: Array<PlaylistEntry> | null, uploader: string | null, channel: string | null, viewCount: bigint | null, likeCount: bigint | null, description: string | null, uploadDate: string | null, channelUrl: string | null, channelId: string | null, storyboards: Array<Storyboard> | null, chapters: Array<Chapter> | null, };
