// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fragment } from "./Fragment";

export type VideoFormat = { formatId: string, ext: string, resolution: string | null, fps: number | null, vcodec: string | null, acodec: string | null, filesize: bigint | null, filesizeApprox: bigint | null, tbr: number | null, vbr: number | null, abr: number | null, asr: number | null, hasVideo: boolean, hasAudio: boolean, quality: number | null, formatNote: string | null, rows: number | null, columns: number | null, fragments: Array<Fragment> | null, };
