<script lang="ts">
  import { t } from '$lib/i18n';
  import { invoke } from '@tauri-apps/api/core';
  import { onMount } from 'svelte';
  import Icon from '$lib/components/ui/Icon.svelte';
  import HighlightText from '$lib/components/ui/HighlightText.svelte';
  import SettingsCard from '$lib/components/settings/SettingsCard.svelte';
  import Toggle from '$lib/components/ui/Toggle.svelte';

  interface Props {
    searchQuery: string;
  }

  let { searchQuery }: Props = $props();

  interface PodcastSettingsData {
    enabled: boolean;
    subtitleLang: string;
    ttsVoice: string;
    ttsRate: string;
    claudePrompt: string | null;
    masteringEnabled: boolean;
    autoGenerate: boolean;
  }

  let podcastSettings = $state<PodcastSettingsData>({
    enabled: false,
    subtitleLang: 'en',
    ttsVoice: 'en-US-AndrewMultilingualNeural',
    ttsRate: '+0%',
    claudePrompt: null,
    masteringEnabled: true,
    autoGenerate: false,
  });
  let loading = $state(true);
  let saving = $state(false);

  onMount(() => {
    loadSettings();
  });

  async function loadSettings() {
    loading = true;
    try {
      podcastSettings = await invoke<PodcastSettingsData>('get_podcast_settings');
    } catch (err) {
      console.error('Failed to load podcast settings:', err);
    } finally {
      loading = false;
    }
  }

  async function saveSettings() {
    saving = true;
    try {
      await invoke('set_podcast_settings', { settings: podcastSettings });
    } catch (err) {
      console.error('Failed to save podcast settings:', err);
    } finally {
      saving = false;
    }
  }

  async function updateField<K extends keyof PodcastSettingsData>(
    key: K,
    value: PodcastSettingsData[K]
  ) {
    podcastSettings[key] = value;
    await saveSettings();
  }
</script>

<SettingsCard icon="headphones" class="podcast-settings-card">
  {#snippet title()}
    <HighlightText text={$t('settings.podcast.title')} highlight={searchQuery} />
  {/snippet}
  {#snippet description()}
    <HighlightText
      text={$t('settings.podcast.enabledDescription')}
      highlight={searchQuery}
    />
  {/snippet}
  {#snippet headerAction()}
    <Toggle
      checked={podcastSettings.enabled}
      onchange={(v) => updateField('enabled', v)}
      disabled={loading}
    />
  {/snippet}

  {#if podcastSettings.enabled}
    <div class="podcast-options">
      <div class="option-row">
        <div class="option-info">
          <span class="option-label">
            <HighlightText text={$t('settings.podcast.autoGenerate')} highlight={searchQuery} />
          </span>
          <span class="option-desc">
            <HighlightText
              text={$t('settings.podcast.autoGenerateDescription')}
              highlight={searchQuery}
            />
          </span>
        </div>
        <Toggle
          checked={podcastSettings.autoGenerate}
          onchange={(v) => updateField('autoGenerate', v)}
        />
      </div>

      <div class="option-row">
        <div class="option-info">
          <span class="option-label">
            <HighlightText text={$t('settings.podcast.subtitleLang')} highlight={searchQuery} />
          </span>
          <span class="option-desc">
            <HighlightText
              text={$t('settings.podcast.subtitleLangDescription')}
              highlight={searchQuery}
            />
          </span>
        </div>
        <input
          class="text-input"
          type="text"
          value={podcastSettings.subtitleLang}
          onchange={(e) => updateField('subtitleLang', e.currentTarget.value)}
          placeholder="en"
        />
      </div>

      <div class="option-row">
        <div class="option-info">
          <span class="option-label">
            <HighlightText text={$t('settings.podcast.ttsVoice')} highlight={searchQuery} />
          </span>
          <span class="option-desc">
            <HighlightText
              text={$t('settings.podcast.ttsVoiceDescription')}
              highlight={searchQuery}
            />
          </span>
        </div>
        <input
          class="text-input wide"
          type="text"
          value={podcastSettings.ttsVoice}
          onchange={(e) => updateField('ttsVoice', e.currentTarget.value)}
          placeholder="en-US-AndrewMultilingualNeural"
        />
      </div>

      <div class="option-row">
        <div class="option-info">
          <span class="option-label">
            <HighlightText text={$t('settings.podcast.ttsRate')} highlight={searchQuery} />
          </span>
          <span class="option-desc">
            <HighlightText
              text={$t('settings.podcast.ttsRateDescription')}
              highlight={searchQuery}
            />
          </span>
        </div>
        <input
          class="text-input"
          type="text"
          value={podcastSettings.ttsRate}
          onchange={(e) => updateField('ttsRate', e.currentTarget.value)}
          placeholder="+0%"
        />
      </div>

      <div class="option-row">
        <div class="option-info">
          <span class="option-label">
            <HighlightText text={$t('settings.podcast.mastering')} highlight={searchQuery} />
          </span>
          <span class="option-desc">
            <HighlightText
              text={$t('settings.podcast.masteringDescription')}
              highlight={searchQuery}
            />
          </span>
        </div>
        <Toggle
          checked={podcastSettings.masteringEnabled}
          onchange={(v) => updateField('masteringEnabled', v)}
        />
      </div>
    </div>
  {/if}
</SettingsCard>

<style>
  .podcast-options {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }

  .option-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 10px 12px;
    border-radius: var(--radius-md, 8px);
    transition: background 0.15s ease;
  }

  .option-row:hover {
    background: rgba(255, 255, 255, 0.03);
  }

  .option-info {
    display: flex;
    flex-direction: column;
    gap: 2px;
    min-width: 0;
    flex: 1;
  }

  .option-label {
    font-size: var(--text-sm, 13px);
    font-weight: 500;
    color: rgba(255, 255, 255, 0.9);
  }

  .option-desc {
    font-size: var(--text-xs, 11px);
    color: rgba(255, 255, 255, 0.45);
    line-height: 1.3;
  }

  .text-input {
    width: 80px;
    padding: 6px 10px;
    border-radius: var(--radius-sm, 6px);
    background: rgba(255, 255, 255, 0.06);
    border: 1px solid rgba(255, 255, 255, 0.08);
    color: rgba(255, 255, 255, 0.9);
    font-size: var(--text-sm, 12px);
    font-family: inherit;
    outline: none;
    transition: all 0.15s ease;
    flex-shrink: 0;
  }

  .text-input:focus {
    border-color: var(--accent-color, rgba(255, 255, 255, 0.25));
    background: rgba(255, 255, 255, 0.08);
  }

  .text-input.wide {
    width: 220px;
  }

  @media (max-width: 640px) {
    .option-row {
      flex-direction: column;
      align-items: flex-start;
      gap: 8px;
    }

    .text-input,
    .text-input.wide {
      width: 100%;
    }
  }
</style>
